// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Player.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


using _System = global::System;
using _Microsoft = global::Microsoft;

#pragma warning disable 1591

namespace IceCompactId
{
}

namespace FootStone
{
    namespace GrainInterfaces
    {
        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1032")]
#if !SILVERLIGHT
        [_System.Serializable]
#endif
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
        public partial class PlayerNotExsit : Ice.UserException
        {
            #region Constructors

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public PlayerNotExsit()
            {
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public PlayerNotExsit(_System.Exception ex__) : base(ex__)
            {
            }
#if !SILVERLIGHT

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public PlayerNotExsit(_System.Runtime.Serialization.SerializationInfo info__, _System.Runtime.Serialization.StreamingContext context__) : base(info__, context__)
            {
            }
#endif

            #endregion

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public override string ice_name()
            {
                return "FootStone::GrainInterfaces::PlayerNotExsit";
            }

            #region Object members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public override int GetHashCode()
            {
                int h__ = 5381;
                IceInternal.HashUtil.hashAdd(ref h__, "::FootStone::GrainInterfaces::PlayerNotExsit");
                return h__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public override bool Equals(object other__)
            {
                if(other__ == null)
                {
                    return false;
                }
                if(object.ReferenceEquals(this, other__))
                {
                    return true;
                }
                PlayerNotExsit o__ = other__ as PlayerNotExsit;
                if(o__ == null)
                {
                    return false;
                }
                return true;
            }

            #endregion

            #region Comparison members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public static bool operator==(PlayerNotExsit lhs__, PlayerNotExsit rhs__)
            {
                return Equals(lhs__, rhs__);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public static bool operator!=(PlayerNotExsit lhs__, PlayerNotExsit rhs__)
            {
                return !Equals(lhs__, rhs__);
            }

            #endregion

            #region Marshaling support

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            protected override void writeImpl__(IceInternal.BasicStream os__)
            {
                os__.startWriteSlice("::FootStone::GrainInterfaces::PlayerNotExsit", -1, true);
                os__.endWriteSlice();
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            protected override void readImpl__(IceInternal.BasicStream is__)
            {
                is__.startReadSlice();
                is__.endReadSlice();
            }

            #endregion
        }

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
#if !SILVERLIGHT
        [_System.Serializable]
#endif
        public partial class Item : _System.ICloneable
        {
            #region Slice data members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public string id;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public string name;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public int type;

            #endregion

            #region Constructors

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public Item()
            {
                id = "";
                name = "";
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public Item(string id, string name, int type)
            {
                this.id = id;
                this.name = name;
                this.type = type;
            }

            #endregion

            #region ICloneable members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public object Clone()
            {
                return MemberwiseClone();
            }

            #endregion

            #region Object members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public override int GetHashCode()
            {
                int h__ = 5381;
                IceInternal.HashUtil.hashAdd(ref h__, "::FootStone::GrainInterfaces::Item");
                IceInternal.HashUtil.hashAdd(ref h__, id);
                IceInternal.HashUtil.hashAdd(ref h__, name);
                IceInternal.HashUtil.hashAdd(ref h__, type);
                return h__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public override bool Equals(object other__)
            {
                if(object.ReferenceEquals(this, other__))
                {
                    return true;
                }
                if(other__ == null)
                {
                    return false;
                }
                if(GetType() != other__.GetType())
                {
                    return false;
                }
                Item o__ = (Item)other__;
                if(id == null)
                {
                    if(o__.id != null)
                    {
                        return false;
                    }
                }
                else
                {
                    if(!id.Equals(o__.id))
                    {
                        return false;
                    }
                }
                if(name == null)
                {
                    if(o__.name != null)
                    {
                        return false;
                    }
                }
                else
                {
                    if(!name.Equals(o__.name))
                    {
                        return false;
                    }
                }
                if(!type.Equals(o__.type))
                {
                    return false;
                }
                return true;
            }

            #endregion

            #region Comparison members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public static bool operator==(Item lhs__, Item rhs__)
            {
                return Equals(lhs__, rhs__);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public static bool operator!=(Item lhs__, Item rhs__)
            {
                return !Equals(lhs__, rhs__);
            }

            #endregion

            #region Marshalling support

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public void write__(IceInternal.BasicStream os__)
            {
                os__.writeString(id);
                os__.writeString(name);
                os__.writeInt(type);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public void read__(IceInternal.BasicStream is__)
            {
                id = is__.readString();
                name = is__.readString();
                type = is__.readInt();
            }
            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public static void write__(IceInternal.BasicStream os__, Item v__)
            {
                if(v__ == null)
                {
                    nullMarshalValue__.write__(os__);
                }
                else
                {
                    v__.write__(os__);
                }
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public static Item read__(IceInternal.BasicStream is__, Item v__)
            {
                if(v__ == null)
                {
                    v__ = new Item();
                }
                v__.read__(is__);
                return v__;
            }
            
            private static readonly Item nullMarshalValue__ = new Item();

            #endregion
        }

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
#if !SILVERLIGHT
        [_System.Serializable]
#endif
        public partial struct PlayerMaster
        {
            #region Slice data members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public int hp;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public int mp;

            #endregion

            #region Constructor

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public PlayerMaster(int hp, int mp)
            {
                this.hp = hp;
                this.mp = mp;
            }

            #endregion

            #region Object members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public override int GetHashCode()
            {
                int h__ = 5381;
                IceInternal.HashUtil.hashAdd(ref h__, "::FootStone::GrainInterfaces::PlayerMaster");
                IceInternal.HashUtil.hashAdd(ref h__, hp);
                IceInternal.HashUtil.hashAdd(ref h__, mp);
                return h__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public override bool Equals(object other__)
            {
                if(!(other__ is PlayerMaster))
                {
                    return false;
                }
                PlayerMaster o__ = (PlayerMaster)other__;
                if(!hp.Equals(o__.hp))
                {
                    return false;
                }
                if(!mp.Equals(o__.mp))
                {
                    return false;
                }
                return true;
            }

            #endregion

            #region Comparison members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public static bool operator==(PlayerMaster lhs__, PlayerMaster rhs__)
            {
                return Equals(lhs__, rhs__);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public static bool operator!=(PlayerMaster lhs__, PlayerMaster rhs__)
            {
                return !Equals(lhs__, rhs__);
            }

            #endregion

            #region Marshalling support

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public void write__(IceInternal.BasicStream os__)
            {
                os__.writeInt(hp);
                os__.writeInt(mp);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public void read__(IceInternal.BasicStream is__)
            {
                hp = is__.readInt();
                mp = is__.readInt();
            }

            #endregion
        }

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
#if !SILVERLIGHT
        [_System.Serializable]
#endif
        public partial class PlayerInfo : _System.ICloneable
        {
            #region Slice data members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public string Key;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public string Name;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public FootStone.GrainInterfaces.PlayerMaster playerMaster;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public _System.Collections.Generic.List<FootStone.GrainInterfaces.Item> items;

            #endregion

            #region Constructors

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public PlayerInfo()
            {
                Key = "";
                Name = "";
                playerMaster = new FootStone.GrainInterfaces.PlayerMaster();
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public PlayerInfo(string Key, string Name, FootStone.GrainInterfaces.PlayerMaster playerMaster, _System.Collections.Generic.List<FootStone.GrainInterfaces.Item> items)
            {
                this.Key = Key;
                this.Name = Name;
                this.playerMaster = playerMaster;
                this.items = items;
            }

            #endregion

            #region ICloneable members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public object Clone()
            {
                return MemberwiseClone();
            }

            #endregion

            #region Object members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public override int GetHashCode()
            {
                int h__ = 5381;
                IceInternal.HashUtil.hashAdd(ref h__, "::FootStone::GrainInterfaces::PlayerInfo");
                IceInternal.HashUtil.hashAdd(ref h__, Key);
                IceInternal.HashUtil.hashAdd(ref h__, Name);
                IceInternal.HashUtil.hashAdd(ref h__, playerMaster);
                IceInternal.HashUtil.hashAdd(ref h__, items);
                return h__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public override bool Equals(object other__)
            {
                if(object.ReferenceEquals(this, other__))
                {
                    return true;
                }
                if(other__ == null)
                {
                    return false;
                }
                if(GetType() != other__.GetType())
                {
                    return false;
                }
                PlayerInfo o__ = (PlayerInfo)other__;
                if(Key == null)
                {
                    if(o__.Key != null)
                    {
                        return false;
                    }
                }
                else
                {
                    if(!Key.Equals(o__.Key))
                    {
                        return false;
                    }
                }
                if(Name == null)
                {
                    if(o__.Name != null)
                    {
                        return false;
                    }
                }
                else
                {
                    if(!Name.Equals(o__.Name))
                    {
                        return false;
                    }
                }
                if(!playerMaster.Equals(o__.playerMaster))
                {
                    return false;
                }
                if(items == null)
                {
                    if(o__.items != null)
                    {
                        return false;
                    }
                }
                else
                {
                    if(!IceUtilInternal.Collections.SequenceEquals(items, o__.items))
                    {
                        return false;
                    }
                }
                return true;
            }

            #endregion

            #region Comparison members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public static bool operator==(PlayerInfo lhs__, PlayerInfo rhs__)
            {
                return Equals(lhs__, rhs__);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public static bool operator!=(PlayerInfo lhs__, PlayerInfo rhs__)
            {
                return !Equals(lhs__, rhs__);
            }

            #endregion

            #region Marshalling support

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public void write__(IceInternal.BasicStream os__)
            {
                os__.writeString(Key);
                os__.writeString(Name);
                playerMaster.write__(os__);
                FootStone.GrainInterfaces.ItemListHelper.write(os__, items);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public void read__(IceInternal.BasicStream is__)
            {
                Key = is__.readString();
                Name = is__.readString();
                playerMaster.read__(is__);
                items = FootStone.GrainInterfaces.ItemListHelper.read(is__);
            }
            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public static void write__(IceInternal.BasicStream os__, PlayerInfo v__)
            {
                if(v__ == null)
                {
                    nullMarshalValue__.write__(os__);
                }
                else
                {
                    v__.write__(os__);
                }
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
            public static PlayerInfo read__(IceInternal.BasicStream is__, PlayerInfo v__)
            {
                if(v__ == null)
                {
                    v__ = new PlayerInfo();
                }
                v__.read__(is__);
                return v__;
            }
            
            private static readonly PlayerInfo nullMarshalValue__ = new PlayerInfo();

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
        public partial interface Player : Ice.Object, PlayerOperations_, PlayerOperationsNC_
        {
        }
    }
}

namespace FootStone
{
    namespace GrainInterfaces
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public delegate void Callback_Player_getPlayerInfo(FootStone.GrainInterfaces.PlayerInfo ret__);
    }
}

namespace FootStone
{
    namespace GrainInterfaces
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public interface PlayerPrx : Ice.ObjectPrx
        {
            FootStone.GrainInterfaces.PlayerInfo getPlayerInfo(string playerId);
            FootStone.GrainInterfaces.PlayerInfo getPlayerInfo(string playerId, _System.Collections.Generic.Dictionary<string, string> context__);

            Ice.AsyncResult<FootStone.GrainInterfaces.Callback_Player_getPlayerInfo> begin_getPlayerInfo(string playerId);
            Ice.AsyncResult<FootStone.GrainInterfaces.Callback_Player_getPlayerInfo> begin_getPlayerInfo(string playerId, _System.Collections.Generic.Dictionary<string, string> ctx__);

            Ice.AsyncResult begin_getPlayerInfo(string playerId, Ice.AsyncCallback cb__, object cookie__);
            Ice.AsyncResult begin_getPlayerInfo(string playerId, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

            FootStone.GrainInterfaces.PlayerInfo end_getPlayerInfo(Ice.AsyncResult r__);
        }
    }
}

namespace FootStone
{
    namespace GrainInterfaces
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public interface PlayerOperations_
        {
            void getPlayerInfo_async(FootStone.GrainInterfaces.AMD_Player_getPlayerInfo cb__, string playerId, Ice.Current current__);
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public interface PlayerOperationsNC_
        {
            void getPlayerInfo_async(FootStone.GrainInterfaces.AMD_Player_getPlayerInfo cb__, string playerId);
        }
    }
}

namespace FootStone
{
    namespace GrainInterfaces
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public sealed class ItemListHelper
        {
            public static void write(IceInternal.BasicStream os__, _System.Collections.Generic.List<FootStone.GrainInterfaces.Item> v__)
            {
                if(v__ == null)
                {
                    os__.writeSize(0);
                }
                else
                {
                    os__.writeSize(v__.Count);
                    for(int ix__ = 0; ix__ < v__.Count; ++ix__)
                    {
                        (v__[ix__] == null ? new FootStone.GrainInterfaces.Item() : v__[ix__]).write__(os__);
                    }
                }
            }

            public static _System.Collections.Generic.List<FootStone.GrainInterfaces.Item> read(IceInternal.BasicStream is__)
            {
                _System.Collections.Generic.List<FootStone.GrainInterfaces.Item> v__;
                {
                    int szx__ = is__.readAndCheckSeqSize(6);
                    v__ = new _System.Collections.Generic.List<FootStone.GrainInterfaces.Item>(szx__);
                    for(int ix__ = 0; ix__ < szx__; ++ix__)
                    {
                        FootStone.GrainInterfaces.Item val__ = new FootStone.GrainInterfaces.Item();
                        val__.read__(is__);
                        v__.Add(val__);
                    }
                }
                return v__;
            }
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public sealed class PlayerPrxHelper : Ice.ObjectPrxHelperBase, PlayerPrx
        {
            #region Synchronous operations

            public FootStone.GrainInterfaces.PlayerInfo getPlayerInfo(string playerId)
            {
                return this.getPlayerInfo(playerId, null, false);
            }

            public FootStone.GrainInterfaces.PlayerInfo getPlayerInfo(string playerId, _System.Collections.Generic.Dictionary<string, string> context__)
            {
                return this.getPlayerInfo(playerId, context__, true);
            }

            private FootStone.GrainInterfaces.PlayerInfo getPlayerInfo(string playerId, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitCtx__)
            {
                checkTwowayOnly__(__getPlayerInfo_name);
                return end_getPlayerInfo(begin_getPlayerInfo(playerId, context__, explicitCtx__, true, null, null));
            }

            #endregion

            #region Asynchronous operations

            public Ice.AsyncResult<FootStone.GrainInterfaces.Callback_Player_getPlayerInfo> begin_getPlayerInfo(string playerId)
            {
                return begin_getPlayerInfo(playerId, null, false, false, null, null);
            }

            public Ice.AsyncResult<FootStone.GrainInterfaces.Callback_Player_getPlayerInfo> begin_getPlayerInfo(string playerId, _System.Collections.Generic.Dictionary<string, string> ctx__)
            {
                return begin_getPlayerInfo(playerId, ctx__, true, false, null, null);
            }

            public Ice.AsyncResult begin_getPlayerInfo(string playerId, Ice.AsyncCallback cb__, object cookie__)
            {
                return begin_getPlayerInfo(playerId, null, false, false, cb__, cookie__);
            }

            public Ice.AsyncResult begin_getPlayerInfo(string playerId, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
            {
                return begin_getPlayerInfo(playerId, ctx__, true, false, cb__, cookie__);
            }

            private const string __getPlayerInfo_name = "getPlayerInfo";

            public FootStone.GrainInterfaces.PlayerInfo end_getPlayerInfo(Ice.AsyncResult r__)
            {
                IceInternal.OutgoingAsync outAsync__ = IceInternal.OutgoingAsync.check(r__, this, __getPlayerInfo_name);
                try
                {
                    if(!outAsync__.wait())
                    {
                        try
                        {
                            outAsync__.throwUserException();
                        }
                        catch(FootStone.GrainInterfaces.PlayerNotExsit)
                        {
                            throw;
                        }
                        catch(Ice.UserException ex__)
                        {
                            throw new Ice.UnknownUserException(ex__.ice_name(), ex__);
                        }
                    }
                    FootStone.GrainInterfaces.PlayerInfo ret__;
                    IceInternal.BasicStream is__ = outAsync__.startReadParams();
                    ret__ = null;
                    ret__ = FootStone.GrainInterfaces.PlayerInfo.read__(is__, ret__);
                    outAsync__.endReadParams();
                    return ret__;
                }
                finally
                {
                    outAsync__.cacheMessageBuffers();
                }
            }

            private Ice.AsyncResult<FootStone.GrainInterfaces.Callback_Player_getPlayerInfo> begin_getPlayerInfo(string playerId, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, bool synchronous__, Ice.AsyncCallback cb__, object cookie__)
            {
                checkAsyncTwowayOnly__(__getPlayerInfo_name);
                IceInternal.TwowayOutgoingAsync<FootStone.GrainInterfaces.Callback_Player_getPlayerInfo> result__ =  getTwowayOutgoingAsync<FootStone.GrainInterfaces.Callback_Player_getPlayerInfo>(__getPlayerInfo_name, getPlayerInfo_completed__, cookie__);
                if(cb__ != null)
                {
                    result__.whenCompletedWithAsyncCallback(cb__);
                }
                try
                {
                    result__.prepare(__getPlayerInfo_name, Ice.OperationMode.Idempotent, ctx__, explicitContext__, synchronous__);
                    IceInternal.BasicStream os__ = result__.startWriteParams(Ice.FormatType.DefaultFormat);
                    os__.writeString(playerId);
                    result__.endWriteParams();
                    result__.invoke();
                }
                catch(Ice.Exception ex__)
                {
                    result__.abort(ex__);
                }
                return result__;
            }

            private void getPlayerInfo_completed__(Ice.AsyncResult r__, FootStone.GrainInterfaces.Callback_Player_getPlayerInfo cb__, Ice.ExceptionCallback excb__)
            {
                FootStone.GrainInterfaces.PlayerInfo ret__;
                try
                {
                    ret__ = end_getPlayerInfo(r__);
                }
                catch(Ice.Exception ex__)
                {
                    if(excb__ != null)
                    {
                        excb__(ex__);
                    }
                    return;
                }
                if(cb__ != null)
                {
                    cb__(ret__);
                }
            }

            #endregion

            #region Checked and unchecked cast operations

            public static PlayerPrx checkedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                PlayerPrx r = b as PlayerPrx;
                if((r == null) && b.ice_isA(ice_staticId()))
                {
                    PlayerPrxHelper h = new PlayerPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static PlayerPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                PlayerPrx r = b as PlayerPrx;
                if((r == null) && b.ice_isA(ice_staticId(), ctx))
                {
                    PlayerPrxHelper h = new PlayerPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static PlayerPrx checkedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId()))
                    {
                        PlayerPrxHelper h = new PlayerPrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static PlayerPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId(), ctx))
                    {
                        PlayerPrxHelper h = new PlayerPrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static PlayerPrx uncheckedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                PlayerPrx r = b as PlayerPrx;
                if(r == null)
                {
                    PlayerPrxHelper h = new PlayerPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static PlayerPrx uncheckedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                PlayerPrxHelper h = new PlayerPrxHelper();
                h.copyFrom__(bb);
                return h;
            }

            public static readonly string[] ids__ =
            {
                "::FootStone::GrainInterfaces::Player",
                "::Ice::Object"
            };

            public static string ice_staticId()
            {
                return ids__[0];
            }

            #endregion

            #region Marshaling support

            public static void write__(IceInternal.BasicStream os__, PlayerPrx v__)
            {
                os__.writeProxy(v__);
            }

            public static PlayerPrx read__(IceInternal.BasicStream is__)
            {
                Ice.ObjectPrx proxy = is__.readProxy();
                if(proxy != null)
                {
                    PlayerPrxHelper result = new PlayerPrxHelper();
                    result.copyFrom__(proxy);
                    return result;
                }
                return null;
            }

            #endregion
        }
    }
}

namespace FootStone
{
    namespace GrainInterfaces
    {
        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public abstract class PlayerDisp_ : Ice.ObjectImpl, Player
        {
            #region Slice operations

            public void getPlayerInfo_async(FootStone.GrainInterfaces.AMD_Player_getPlayerInfo cb__, string playerId)
            {
                getPlayerInfo_async(cb__, playerId, Ice.ObjectImpl.defaultCurrent);
            }

            public abstract void getPlayerInfo_async(FootStone.GrainInterfaces.AMD_Player_getPlayerInfo cb__, string playerId, Ice.Current current__);

            #endregion

            #region Slice type-related members

            public static new readonly string[] ids__ = 
            {
                "::FootStone::GrainInterfaces::Player",
                "::Ice::Object"
            };

            public override bool ice_isA(string s)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            public override bool ice_isA(string s, Ice.Current current__)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            public override string[] ice_ids()
            {
                return ids__;
            }

            public override string[] ice_ids(Ice.Current current__)
            {
                return ids__;
            }

            public override string ice_id()
            {
                return ids__[0];
            }

            public override string ice_id(Ice.Current current__)
            {
                return ids__[0];
            }

            public static new string ice_staticId()
            {
                return ids__[0];
            }

            #endregion

            #region Operation dispatch

            [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
            public static Ice.DispatchStatus getPlayerInfo___(Player obj__, IceInternal.Incoming inS__, Ice.Current current__)
            {
                Ice.ObjectImpl.checkMode__(Ice.OperationMode.Idempotent, current__.mode);
                IceInternal.BasicStream is__ = inS__.startReadParams();
                string playerId;
                playerId = is__.readString();
                inS__.endReadParams();
                AMD_Player_getPlayerInfo cb__ = new _AMD_Player_getPlayerInfo(inS__);
                try
                {
                    obj__.getPlayerInfo_async(cb__, playerId, current__);
                }
                catch(_System.Exception ex__)
                {
                    cb__.ice_exception(ex__);
                }
                return Ice.DispatchStatus.DispatchAsync;
            }

            private static string[] all__ =
            {
                "getPlayerInfo",
                "ice_id",
                "ice_ids",
                "ice_isA",
                "ice_ping"
            };

            public override Ice.DispatchStatus dispatch__(IceInternal.Incoming inS__, Ice.Current current__)
            {
                int pos = _System.Array.BinarySearch(all__, current__.operation, IceUtilInternal.StringUtil.OrdinalStringComparer);
                if(pos < 0)
                {
                    throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
                }

                switch(pos)
                {
                    case 0:
                    {
                        return getPlayerInfo___(this, inS__, current__);
                    }
                    case 1:
                    {
                        return Ice.ObjectImpl.ice_id___(this, inS__, current__);
                    }
                    case 2:
                    {
                        return Ice.ObjectImpl.ice_ids___(this, inS__, current__);
                    }
                    case 3:
                    {
                        return Ice.ObjectImpl.ice_isA___(this, inS__, current__);
                    }
                    case 4:
                    {
                        return Ice.ObjectImpl.ice_ping___(this, inS__, current__);
                    }
                }

                _System.Diagnostics.Debug.Assert(false);
                throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
            }

            #endregion

            #region Marshaling support

            protected override void writeImpl__(IceInternal.BasicStream os__)
            {
                os__.startWriteSlice(ice_staticId(), -1, true);
                os__.endWriteSlice();
            }

            protected override void readImpl__(IceInternal.BasicStream is__)
            {
                is__.startReadSlice();
                is__.endReadSlice();
            }

            #endregion
        }
    }
}

namespace FootStone
{
    namespace GrainInterfaces
    {
        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public interface AMD_Player_getPlayerInfo : Ice.AMDCallback
        {
            void ice_response(FootStone.GrainInterfaces.PlayerInfo ret__);
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        class _AMD_Player_getPlayerInfo : IceInternal.IncomingAsync, AMD_Player_getPlayerInfo
        {
            public _AMD_Player_getPlayerInfo(IceInternal.Incoming inc) : base(inc)
            {
            }

            public void ice_response(FootStone.GrainInterfaces.PlayerInfo ret__)
            {
                if(validateResponse__(true))
                {
                    try
                    {
                        IceInternal.BasicStream os__ = startWriteParams__(Ice.FormatType.DefaultFormat);
                        FootStone.GrainInterfaces.PlayerInfo.write__(os__, ret__);
                        endWriteParams__(true);
                    }
                    catch(Ice.LocalException ex__)
                    {
                        exception__(ex__);
                        return;
                    }
                    response__();
                }
            }

            override public void ice_exception(_System.Exception ex)
            {
                try
                {
                    throw ex;
                }
                catch(FootStone.GrainInterfaces.PlayerNotExsit ex__)
                {
                    if(validateResponse__(false))
                    {
                        writeUserException__(ex__, Ice.FormatType.DefaultFormat);
                        response__();
                    }
                }
                catch(_System.Exception ex__)
                {
                    base.ice_exception(ex__);
                }
            }
        }
    }
}
